# IP Address Base for private network
ip_addr_base = "192.168.57.10%d"

# Name for the box
box = "ubuntu/trusty64"

# Load the next level Vagrantfile (cb version)
load '../version'

# Read and execute the top level Vagrantfile
external = File.read '../../Vagrantfile'
eval external
