# IP Address Base for private network
ip_addr_base = "192.168.40.10%d"

# Name for the box
box = "emyl/win2008r2"

# Couchbase Server Version
Version = "???"

# Read and execute the top level Vagrantfile
external = File.read '../Vagrantfile'
eval external
