Vagrant.configure("2") do |config|
  # IP Address Base for private network
  ip_addr_base = "192.168.69.10%d"

  box = "hfm4/centos7"

  # Load the next level Vagrantfile (cb version)
  load '../version'

  # URL base for the Couchbase download URL
  Url= "http://packages.northscale.com/latestbuilds/3.0.0/couchbase-server-enterprise_centos6_x86_64_#{Version}"

  # Read and execute the top level Vagrantfile
  external2 = File.read '../../Vagrantfile'
  eval external2
end
