# IP Address Base for private network
ip_addr_base = "192.168.67.10%d"

# Download the initial box from this url
box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"

# Name for the box
box = "centos64_x64"

# Load the next level Vagrantfile (cb version)
load '../version'

# Read and execute the top level Vagrantfile
external = File.read '../../Vagrantfile'
eval external
