Vagrant.configure("2") do |config|
  # IP Address Base for private network
  ip_addr_base = "192.168.57.10%d"

  box = "ubuntu/trusty64"

  # Load the next level Vagrantfile (cb version)
  load '../version'

  # Read and execute the top level Vagrantfile
  external2 = File.read '../../Vagrantfile'
  eval external2
end
